openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Notification Service API'
  description: Provides endpoints for long-polling and receive real-time notifications

paths:
  /notifications:
    get:
      security:
        - BearerAuth: []
      summary: Subscribe to notifications
      description: By calling this endpoint the client subscribes to notifications which will be streamed to the client without terminating the connection
      responses:
        200:
          description: If authentication was successful and the it also went through request validation, the response code will be 200 and event stream will start
          content:
            # We are using text/event-stream here, notifications will be delivered one-by-one as soon as they become available
            application/json:
              schema:
                type: string
        401:
          description: Authentication was unsuccessful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      description: General purpose error object
      type: object
      required:
        - error
      properties:
        error:
          description: The machine interpretable error code
          type: string
        message:
          description: A human readable error message
          type: string
        context:
          description: Optional error context information
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer